### ISSUE TITLE
ESPHome - Bad parameter restore_mode for output

### ISSUE THREAD

**Issue by jcz1** [LaskaKit/Weather_Station_Mini#5]
In examples there is configuration not compatible with ESPHome 2024.11.2. Parameter restore_mode is not available for output, but it is for switch. This is working for me and it is necessary for BME688 sensor.

```
# Enable I2C power
#output:
switch:
  - platform: gpio
    pin: GPIO3 
    id: my_output
    restore_mode: ALWAYS_ON  # Keep the pin high after boot
```

https://github.com/LaskaKit/Weather_Station_Mini/blob/main/SW/esphome/meteo-station.yaml
